---
title: 使用R求解常微分方程
date: '`r Sys.Date()`'
output:
    html_document:
        toc: TRUE
---

# 使用的软件包

```{r message=FALSE}
require(tidyverse)
require(deSolve)
```

# 模型示例

## 拟一级动力学降解动力学

拟一级降解动力学可以表示为$\frac{dC}{dt} = -kC$。

```{r}
f1 = function(t, y, parms){
    with(as.list(parms),{
        dy = -1 * parms[1] * y
        return(list(dy))
    })
}

times = seq(0, 5, length.out = 50)
f1_out = ode(
    times = times, # 求解时间
    y = 10, # 初始浓度
    func = f1, # 模型函数
    parms = c(1) # 模型参数
)
```

```{r fig.align='center', fig.height=3.5, fig.width=3.5}
f1_out %>%
    as.data.frame() %>%
    setNames(c("time", "y")) %>%
    ggplot(aes(time, y)) +
    geom_point()
```

## 拟二级动力学降解动力学

拟二级降解动力学可以表示为$\frac{dC}{dt} = -kC^2$。

```{r}
f2 = function(t, y, parms){
    with(as.list(parms),{
        dy = -1 * parms[1] * y^2
        return(list(dy))
    })
}

times = seq(0, 5, length.out = 50)
f2_out = ode(
    times = times, # 求解时间
    y = 10, # 初始浓度
    func = f2, # 模型函数
    parms = c(1) # 模型参数
)
```

```{r fig.align='center', fig.height=3.5, fig.width=3.5}
f2_out %>%
    as.data.frame() %>%
    setNames(c("time", "y")) %>%
    ggplot(aes(time, y)) +
    geom_point()
```

## 反硝化

```{r}
f_n = function(t, y, parms) {
    with(as.list(c(y, parms)), {
        dNO3 = -1 * k1 * NO3
        dNO2 = k1 * NO3 - k2 * NO2
        return(
            list(c(dNO3, dNO2))
        )
    })
}
times = seq(0, 5, length.out = 50)
parms_N = c(k1 = 1, k2 = 0.5)
y_ini = c(NO3 = 10, NO2 = 0)

f_n_out = ode(
    times = times, 
    y = y_ini,
    parms = parms_N,
    func = f_n
)
```

```{r fig.align='center', fig.height=3.5, fig.width=3.5}
f_n_out %>%
    as.data.frame() %>%
    pivot_longer(cols = -1) %>%
    ggplot(aes(time, value, color = name)) +
    geom_point() +
    theme(legend.position = 'top')
```
